services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: virgie
      POSTGRES_PASSWORD: virgie
      POSTGRES_DB:virgie
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
volumes:
  db_data:
